import { ClerkProvider } from '@clerk/nextjs';
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });
import '../globals.css';

import Topbar from '@/components/shared/Topbar';
import LeftSidebar from '@/components/shared/LeftSidebar';
import RightSidebar from '@/components/shared/RightSidebar';
import Bottombar from '@/components/shared/Bottombar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={inter.className}>
          <Topbar />
          <main className="flex flex-row">
            <LeftSidebar />
            <section className="main-container">
              <div className="w-full max-w-4xl bg-sky-700 px-4 py-2 text-white hover:bg-sky-800 sm:px-8 sm:py-3">
                {children}
              </div>
              <div className="w-full max-w-4xl bg-sky-700 px-4 py-2 text-white hover:bg-sky-800 sm:px-8 sm:py-3"></div>
              <div className="w-full max-w-4xl  bg-sky-700 px-4 py-2  text-white hover:bg-sky-800 sm:px-8 sm:py-3"></div>
            </section>
            <RightSidebar />
          </main>
          <Bottombar />
        </body>
      </ClerkProvider>
    </html>
  );
}
